# Structure data
pdb_id = "4LDE"
pdb_path = ""
membrane_protein = true

# Structure parameters 
vdw_radii = "ProtOr"
membrane_thickness = 15

# Mutagenesis data
mutation_data_path = "examples/B2AR_DMS_example/B2AR_processed_scores.csv"
mutation_data_chain = "A"
# Column names in mutagenesis data file (defaults shown, can be customized)
# mutation_residue_col_name = "wildtype"
# mutation_residue_idx_name = "position"
# mutation_col_name = "mutation"
# mutation_type_col_name = "type"
# mutation_score_col_name = "effect"

# Sequence parameters
aaindex_path = "data/aaindex_parsed_small.csv"
